package symmat_test

import (
	"fmt"
	"math/big"
	"os"

	"github.com/ichijohodaka/symmatinv/pkg/symmat"
	"github.com/ichijohodaka/symmatinv/pkg/tape"
)

// 3 次対称行列の逆行列を求める。
//
//	A = [ 4  1  0 ]
//	    [ 1  3  1 ]
//	    [ 0  1  2 ]
func ExampleInverse() {
	inv, err := symmat.Inverse(3)
	if err != nil {
		panic(err)
	}
	tp := inv.Tape()

	// 上三角を行優先で並べる。[a00 a01 a02 a11 a12 a22]
	a := []float64{4, 1, 0, 3, 1, 2}
	out := make([]float64, symmat.NumEntries(3))
	scratch := tape.NewScratch[float64](tp)

	tape.EvalFloat64(tp, a, scratch, out)

	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			fmt.Printf("%8.4f", out[symmat.Index(3, i, j)])
		}
		fmt.Println()
	}
	// Output:
	//   0.2778 -0.1111  0.0556
	//  -0.1111  0.4444 -0.2222
	//   0.0556 -0.2222  0.6111
}

// 同じ命令列に何度も代入する、という本来の使い方。命令列を作るのは一度だけで、
// 作業用配列も使い回す。
func ExampleInverse_manySets() {
	inv, err := symmat.Inverse(3)
	if err != nil {
		panic(err)
	}
	tp := inv.Tape()
	scratch := tape.NewScratch[float64](tp)
	out := make([]float64, symmat.NumEntries(3))

	// a00 だけを動かしながら、逆行列の左上の要素を見る。
	//
	//	A = [ d 1 0 ]   det A = 5d − 2
	//	    [ 1 3 1 ]   (A⁻¹)[0][0] = 5 / (5d − 2)
	//	    [ 0 1 2 ]
	//
	// なので d = 2, 4, 8 に対して 5/8, 5/18, 5/38。
	for _, d := range []float64{2, 4, 8} {
		a := []float64{d, 1, 0, 3, 1, 2}
		tape.EvalFloat64(tp, a, scratch, out)
		fmt.Printf("a00=%.0f のとき (A⁻¹)[0][0] = %.4f\n", d, out[symmat.Index(3, 0, 0)])
	}
	fmt.Printf("1組あたりの演算回数: %d\n", inv.NumInstrs())
	// Output:
	// a00=2 のとき (A⁻¹)[0][0] = 0.6250
	// a00=4 のとき (A⁻¹)[0][0] = 0.2778
	// a00=8 のとき (A⁻¹)[0][0] = 0.1316
	// 1組あたりの演算回数: 29
}

// 有理数で評価すると丸め誤差なしに答えが出る。検算に使う。
func ExampleInverse_exactRationals() {
	inv, err := symmat.Inverse(2)
	if err != nil {
		panic(err)
	}
	tp := inv.Tape()

	// A = [[4,1],[1,2]]、det = 7
	a := []*big.Rat{big.NewRat(4, 1), big.NewRat(1, 1), big.NewRat(2, 1)}
	out := make([]*big.Rat, symmat.NumEntries(2))
	tape.Eval(tape.RatField{}, tp, a, tape.NewScratch[*big.Rat](tp), out)

	fmt.Println(out[0], out[1], out[2])
	// Output:
	// 2/7 -1/7 4/7
}

// 行列式は逆行列と同じ手順から取り出せる。
func ExampleDeterminant() {
	tp, err := symmat.Determinant(3)
	if err != nil {
		panic(err)
	}
	out := make([]float64, 1)
	tape.EvalFloat64(tp, []float64{4, 1, 0, 3, 1, 2}, tape.NewScratch[float64](tp), out)

	fmt.Printf("det = %.0f（演算 %d 回）\n", out[0], tp.NumInstrs())
	// Output:
	// det = 18（演算 13 回）
}

// 分け方を指定する。答えは変わらず、演算回数だけが変わる。
func ExampleInverseWithPlan() {
	for _, s := range []string{"6=3+3", "6=1+5", "6=2+4"} {
		plan, err := symmat.ParsePlan(s)
		if err != nil {
			panic(err)
		}
		inv, err := symmat.InverseWithPlan(6, plan)
		if err != nil {
			panic(err)
		}
		fmt.Printf("%-22s 演算 %d 回\n", plan, inv.NumInstrs())
	}
	// Output:
	// 6=3+3[3=1+2,3=1+2]     演算 229 回
	// 6=1+5[1,5=2+3[2,3=1+2]] 演算 229 回
	// 6=2+4[2,4=2+2]         演算 228 回
}

// 上三角の並びと n×n の行き来。
func ExampleToFull() {
	upper := []float64{1, 2, 3, 4, 5, 6} // [a00 a01 a02 a11 a12 a22]
	full := make([]float64, 9)
	symmat.ToFull(3, upper, full)

	for i := 0; i < 3; i++ {
		fmt.Println(full[i*3 : i*3+3])
	}
	// Output:
	// [1 2 3]
	// [2 4 5]
	// [3 5 6]
}

// 求めた計算手順を Go のソースとして書き出す。自分のリポジトリに置いておけば、
// 次からはコンパイル済みの関数を呼ぶだけで済む。
func ExampleInv_Tape_generateGo() {
	inv, err := symmat.Inverse(2)
	if err != nil {
		panic(err)
	}
	err = tape.GenGo(os.Stdout, inv.Tape(), tape.GoOptions{
		Package: "mypkg",
		Func:    "Inv2",
		Doc:     "Inv2 は 2 次対称行列の逆行列を求める。",
	})
	if err != nil {
		panic(err)
	}
	// Output:
	// // Code generated by symmatinv. DO NOT EDIT.
	//
	// package mypkg
	//
	// // Inv2 は 2 次対称行列の逆行列を求める。
	// //
	// // 入力 v は長さ 3（a00, a01, a11）、出力 out は長さ 3（b00, b01, b11）。
	// // 1回あたりの演算回数: 8 (sub 1, mul 5, neg 1, recip 1)
	// func Inv2(v, out []float64) {
	// 	_ = v[2]
	// 	_ = out[2]
	// 	t0 := v[0] * v[2]
	// 	t1 := v[1] * v[1]
	// 	t2 := t0 - t1
	// 	t3 := 1 / t2
	// 	t4 := v[2] * t3
	// 	t5 := v[1] * t3
	// 	t6 := -t5
	// 	t7 := v[0] * t3
	// 	out[0] = t4 // b00
	// 	out[1] = t6 // b01
	// 	out[2] = t7 // b11
	// }
}
