package tape

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"sort"
	"strings"
)

// GoOptions は Go ソース生成の指定。
type GoOptions struct {
	Package string // パッケージ名（必須）
	Func    string // 関数名（必須）
	Doc     string // 関数のコメント。複数行可。省略すると既定の説明が入る
	Source  string // 「何から生成したか」をファイル先頭のコメントに書きたいとき
}

// GenGo は命令列を Go の関数として書き出す。
//
// 生成される関数の形は
//
//	func <Func>(v, out []float64)
//
// で、v に入力変数を並べ、out に出力が入る。中身は
//
//	t0 := v[0] * v[3]
//	t1 := 1 / t0
//	out[0] = t1
//
// のような代入の並びだけで、分岐もループも確保もない。
//
// 出力に寄与しない命令は Prune で落としてから書き出す（Go では使われない
// 局所変数がコンパイルエラーになるため）。最後に go/format を通すので、
// 戻ってきたソースは構文として必ず正しい。
func GenGo(w io.Writer, t *Tape, opts GoOptions) error {
	if err := t.Validate(); err != nil {
		return err
	}
	if opts.Package == "" {
		return fmt.Errorf("tape: GoOptions.Package が空")
	}
	if opts.Func == "" {
		return fmt.Errorf("tape: GoOptions.Func が空")
	}
	t = t.Prune()

	var b bytes.Buffer
	b.WriteString("// Code generated by symmatinv. DO NOT EDIT.\n")
	if opts.Source != "" {
		for _, line := range strings.Split(strings.TrimRight(opts.Source, "\n"), "\n") {
			fmt.Fprintf(&b, "// %s\n", line)
		}
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)

	doc := opts.Doc
	if doc == "" {
		doc = fmt.Sprintf("%s は入力 v から出力 out を求める。上から順に計算するだけで、"+
			"分岐もループもない。", opts.Func)
	}
	for _, line := range strings.Split(strings.TrimRight(doc, "\n"), "\n") {
		if line == "" {
			b.WriteString("//\n")
		} else {
			fmt.Fprintf(&b, "// %s\n", line)
		}
	}
	b.WriteString("//\n")
	fmt.Fprintf(&b, "// 入力 v は長さ %d", t.NumVars)
	if len(t.VarNames) != 0 {
		fmt.Fprintf(&b, "（%s）", strings.Join(t.VarNames, ", "))
	}
	fmt.Fprintf(&b, "、出力 out は長さ %d", len(t.Outputs))
	if len(t.OutNames) != 0 {
		fmt.Fprintf(&b, "（%s）", strings.Join(t.OutNames, ", "))
	}
	b.WriteString("。\n")
	fmt.Fprintf(&b, "// 1回あたりの演算回数: %d%s\n", t.NumInstrs(), opCountSuffix(t))

	fmt.Fprintf(&b, "func %s(v, out []float64) {\n", opts.Func)
	// 範囲チェックを関数の入口で1回だけ済ませるための定型句。
	if t.NumVars > 0 {
		fmt.Fprintf(&b, "\t_ = v[%d]\n", t.NumVars-1)
	}
	if len(t.Outputs) > 0 {
		fmt.Fprintf(&b, "\t_ = out[%d]\n", len(t.Outputs)-1)
	}
	for i, in := range t.Instrs {
		dst := fmt.Sprintf("t%d", i)
		a := goSlot(t, in.A)
		switch in.Op {
		case OpAdd:
			fmt.Fprintf(&b, "\t%s := %s + %s\n", dst, a, goSlot(t, in.B))
		case OpSub:
			fmt.Fprintf(&b, "\t%s := %s - %s\n", dst, a, goSlot(t, in.B))
		case OpMul:
			fmt.Fprintf(&b, "\t%s := %s * %s\n", dst, a, goSlot(t, in.B))
		case OpNeg:
			fmt.Fprintf(&b, "\t%s := -%s\n", dst, a)
		case OpRecip:
			fmt.Fprintf(&b, "\t%s := 1 / %s\n", dst, a)
		default:
			return fmt.Errorf("tape: 未知の演算 %d", uint8(in.Op))
		}
	}
	for i, s := range t.Outputs {
		line := fmt.Sprintf("\tout[%d] = %s\n", i, goSlot(t, s))
		if len(t.OutNames) != 0 {
			line = fmt.Sprintf("\tout[%d] = %s // %s\n", i, goSlot(t, s), t.OutNames[i])
		}
		b.WriteString(line)
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		// ここに来るのは生成側のバグ。生の出力も添えて原因を追えるようにする。
		return fmt.Errorf("tape: 生成した Go ソースが不正: %w\n--- 生の出力 ---\n%s", err, b.String())
	}
	_, err = w.Write(src)
	return err
}

// goSlot はスロット番号を、生成コード中の式（v[i] か tN）にする。
func goSlot(t *Tape, s int32) string {
	if int(s) < t.NumVars {
		return fmt.Sprintf("v[%d]", s)
	}
	return fmt.Sprintf("t%d", int(s)-t.NumVars)
}

// opCountSuffix は " (mul 12, add 4, ...)" という内訳を作る。逆数は乗算より
// ずっと重いので、総数だけでなく内訳が見えるようにしている。
func opCountSuffix(t *Tape) string {
	counts := t.OpCounts()
	if len(counts) == 0 {
		return ""
	}
	ops := make([]Op, 0, len(counts))
	for op := range counts {
		ops = append(ops, op)
	}
	sort.Slice(ops, func(i, j int) bool { return ops[i] < ops[j] })
	parts := make([]string, 0, len(ops))
	for _, op := range ops {
		parts = append(parts, fmt.Sprintf("%s %d", op, counts[op]))
	}
	return " (" + strings.Join(parts, ", ") + ")"
}
