package tape

import (
	"bytes"
	"fmt"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func TestPruneDropsDeadInstrs(t *testing.T) {
	tp := inv2()
	// 出力に寄与しない命令を2つ足す。
	tp.Instrs = append(tp.Instrs,
		Bin(OpMul, 0, 1), // slot 11 — 誰も読まない
		Un(OpNeg, 11),    // slot 12 — 上を読むが、やはり誰も読まない
	)
	if err := tp.Validate(); err != nil {
		t.Fatalf("Validate: %v", err)
	}

	got := tp.Prune()
	if err := got.Validate(); err != nil {
		t.Fatalf("Prune 後の Validate: %v", err)
	}
	if got.NumInstrs() != 8 {
		t.Errorf("Prune 後の命令数 = %d, want 8", got.NumInstrs())
	}
	if tp.NumInstrs() != 10 {
		t.Errorf("Prune が元の命令列を壊した (命令数 %d)", tp.NumInstrs())
	}

	// 値が変わらないこと。
	vars := []float64{4, 1, 2}
	before := make([]float64, 3)
	EvalFloat64(tp, vars, NewScratch[float64](tp), before)
	after := make([]float64, 3)
	EvalFloat64(got, vars, NewScratch[float64](got), after)
	for i := range before {
		if before[i] != after[i] {
			t.Errorf("out[%d]: Prune 前 %v, 後 %v", i, before[i], after[i])
		}
	}
}

// TestPruneKeepsUnusedVars は、使われていない入力変数が残ることを確かめる。
// 変数の並びは外向きの取り決めなので、勝手に詰めてはいけない。
func TestPruneKeepsUnusedVars(t *testing.T) {
	tp := &Tape{
		NumVars: 3,
		Instrs:  []Instr{Bin(OpAdd, 0, 2)}, // v1 を使わない
		Outputs: []int32{3},
	}
	got := tp.Prune()
	if got.NumVars != 3 {
		t.Errorf("NumVars = %d, want 3", got.NumVars)
	}
	if got.Instrs[0].A != 0 || got.Instrs[0].B != 2 {
		t.Errorf("変数のスロット番号が変わった: %+v", got.Instrs[0])
	}
}

func TestGenGoText(t *testing.T) {
	var buf bytes.Buffer
	err := GenGo(&buf, inv2(), GoOptions{Package: "mypkg", Func: "Inv2"})
	if err != nil {
		t.Fatalf("GenGo: %v", err)
	}
	s := buf.String()
	for _, want := range []string{
		"// Code generated by symmatinv. DO NOT EDIT.",
		"package mypkg",
		"func Inv2(v, out []float64) {",
		"t0 := v[0] * v[2]",
		"t3 := 1 / t2",
		"t6 := -t5",
		"out[0] = t4 // b00",
		"1回あたりの演算回数: 8 (sub 1, mul 5, neg 1, recip 1)",
		"a00, a01, a11",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("生成結果に %q がない:\n%s", want, s)
		}
	}
}

func TestGenGoRejects(t *testing.T) {
	var buf bytes.Buffer
	if err := GenGo(&buf, inv2(), GoOptions{Func: "F"}); err == nil {
		t.Error("Package が空ならエラーになるはず")
	}
	if err := GenGo(&buf, inv2(), GoOptions{Package: "p"}); err == nil {
		t.Error("Func が空ならエラーになるはず")
	}
}

// TestGenGoCompilesAndRuns は生成した Go を実際にビルドして実行し、
// EvalFloat64 と同じ値が出ることを確かめる。コード生成の端から端までの検査。
func TestGenGoCompilesAndRuns(t *testing.T) {
	if testing.Short() {
		t.Skip("-short: go build を走らせるので飛ばす")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go コマンドが見つからない")
	}

	tp := inv2()
	dir := t.TempDir()

	var gen bytes.Buffer
	if err := GenGo(&gen, tp, GoOptions{Package: "main", Func: "inv2"}); err != nil {
		t.Fatalf("GenGo: %v", err)
	}
	write := func(name, content string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	// このリポジトリの go.mod と同じ版にしておく。ここだけ新しくすると、
	// 古い Go を使っている人がテストを走らせたときにここだけ失敗する。
	write("go.mod", "module gentest\n\ngo 1.22\n")
	write("inv2.go", gen.String())
	write("main.go", `package main

import "fmt"

func main() {
	v := []float64{4, 1, 2}
	out := make([]float64, 3)
	inv2(v, out)
	for _, x := range out {
		fmt.Printf("%v\n", x)
	}
}
`)

	cmd := exec.Command("go", "run", ".")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go run: %v\n%s", err, out)
	}

	want := make([]float64, 3)
	EvalFloat64(tp, []float64{4, 1, 2}, NewScratch[float64](tp), want)

	lines := strings.Fields(strings.TrimSpace(string(out)))
	if len(lines) != 3 {
		t.Fatalf("出力が3行でない: %q", out)
	}
	for i, line := range lines {
		got, err := strconv.ParseFloat(line, 64)
		if err != nil {
			t.Fatalf("%d 行目 %q: %v", i, line, err)
		}
		if math.Abs(got-want[i]) > 1e-15 {
			t.Errorf("out[%d]: 生成コード %v, EvalFloat64 %v", i, got, want[i])
		}
	}
}

// TestGenGoPrunes は、死んだ命令があっても生成物がコンパイルできることを
// 確かめる。Go は使われない局所変数をエラーにするので、Prune が効いていないと
// go/format は通っても実際のビルドで落ちる。
func TestGenGoPrunes(t *testing.T) {
	tp := inv2()
	tp.Instrs = append(tp.Instrs, Bin(OpMul, 0, 1))
	var buf bytes.Buffer
	if err := GenGo(&buf, tp, GoOptions{Package: "p", Func: "F"}); err != nil {
		t.Fatalf("GenGo: %v", err)
	}
	if n := strings.Count(buf.String(), ":="); n != 8 {
		t.Errorf("局所変数の数 = %d, want 8:\n%s", n, buf.String())
	}
}

func BenchmarkEvalFloat64(b *testing.B) {
	tp := inv2()
	vars := []float64{4, 1, 2}
	scratch := NewScratch[float64](tp)
	out := make([]float64, 3)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		EvalFloat64(tp, vars, scratch, out)
	}
}

func BenchmarkEvalGeneric(b *testing.B) {
	tp := inv2()
	vars := []float64{4, 1, 2}
	scratch := NewScratch[float64](tp)
	out := make([]float64, 3)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		Eval(Float64Field{}, tp, vars, scratch, out)
	}
}

func ExampleGenGo() {
	var buf bytes.Buffer
	_ = GenGo(&buf, inv2(), GoOptions{
		Package: "example",
		Func:    "Inv2",
		Doc:     "Inv2 は 2 次対称行列の逆行列（上三角）を求める。",
	})
	// 関数の本体だけを見せる。
	s := buf.String()
	fmt.Println(s[strings.Index(s, "func Inv2"):])
	// Output:
	// func Inv2(v, out []float64) {
	// 	_ = v[2]
	// 	_ = out[2]
	// 	t0 := v[0] * v[2]
	// 	t1 := v[1] * v[1]
	// 	t2 := t0 - t1
	// 	t3 := 1 / t2
	// 	t4 := v[2] * t3
	// 	t5 := v[1] * t3
	// 	t6 := -t5
	// 	t7 := v[0] * t3
	// 	out[0] = t4 // b00
	// 	out[1] = t6 // b01
	// 	out[2] = t7 // b11
	// }
}
